let promise_array = ["https://www.w3schools.com/js/js_promise.asp","https://www.w3schools.com/js/tryit.asp?filename=tryjs_promise2","https://www.w3schools.com/js/tryit.asp?filename=tryjs_promise1"
,"https://www.w3schools.com/js/tryit.asp?filename=tryjs_callback7"
,"https://www.w3schools.com/js/tryit.asp?filename=tryjs_promise3"
,"https://www.w3schools.com/js/js_asynchronous.asp"
,"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise"
,"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises"
,"https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous"
,"https://www.geeksforgeeks.org/how-to-synchronously-determine-a-javascript-promises-state/"
,"https://www.geeksforgeeks.org/practice-javascript-online/?ref=shm"
,"https://codebeautify.org/jsvalidate"
,"https://developer.mozilla.org/en-US/docs/Web/API/setTimeout"
,"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function"
,"https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/load_event"
,"https://www.w3schools.com/html/html_quotation_elements.asp"
,"https://www.w3schools.com/html/tryit.asp?filename=tryhtml_formatting_blockquote"
,"https://www.freecodecamp.org/news/javascript-promise-tutorial-how-to-resolve-or-reject-promises-in-js/"
,"https://dev.to/cammanhhoang/what-is-promise-in-javascript-with-real-world-example-dkb"
]